"""Regenerate metadata when the production URL changes: python3 tools/update_metadata.py https://www.e11.consulting/"""
import json
import sys
import re
from pathlib import Path
from html.parser import HTMLParser
from html import unescape
from urllib.parse import urlparse
from xml.sax.saxutils import escape
root = Path(__file__).resolve().parent.parent
origin = sys.argv[1].rstrip('/') + '/' if len(sys.argv) > 1 else 'https://www.e11.consulting/'
assert urlparse(origin).scheme == 'https' and urlparse(origin).netloc
source = (root / 'index.html').read_text()
description = 'Linda Lukackova (Linda Lukačková), business consultant and coach in Bratislava. Leadership, IT recruitment, talent development and project management since 2009.'
meta = f'''<!-- Discovery metadata: generated by tools/update_metadata.py -->
  <link rel="canonical" href="{origin}">
  <meta name="robots" content="index, follow, max-image-preview:large">
  <meta property="og:type" content="profile">
  <meta property="og:title" content="Linda Lukackova | Business Consultant &amp; Coach">
  <meta property="og:description" content="{description}">
  <meta property="og:url" content="{origin}">
  <meta property="og:site_name" content="eleven.consulting">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="Linda Lukackova | Business Consultant &amp; Coach">
  <meta name="twitter:description" content="{description}">
  <link rel="alternate" type="text/markdown" href="index.md" title="Linda Lukackova — professional profile">
  <link rel="describedby" type="text/markdown" href="llms.txt">
'''
person = {'@context':'https://schema.org','@type':'ProfilePage','@id':origin+'#profile','url':origin,'name':'Linda Lukackova | Business Consultant & Coach','inLanguage':'en','mainEntity':{'@type':'Person','@id':origin+'#linda','name':'Linda Lukackova','alternateName':['Linda Lukačková','Linda Lukacková'],'url':origin,'image':origin+'assets/portrait.webp','jobTitle':'Business Consultant, Founder & Business Leader','description':description,'email':'linda@e11.consulting','homeLocation':{'@type':'Place','name':'Bratislava, Slovakia'},'sameAs':['https://www.linkedin.com/in/linda-lukackova/'],'alumniOf':{'@type':'CollegeOrUniversity','name':'University of Economics in Bratislava'},'knowsAbout':['Business consulting','Operations management','IT recruitment','Talent management','Business coaching','Career development','Project management','Psychometric assessments'],'knowsLanguage':[{'@type':'Language','name':'English'}]}}
meta += '  <script type="application/ld+json">\n'+json.dumps(person,ensure_ascii=False,indent=2)+'\n  </script>\n  <!-- End discovery metadata -->'
source = re.sub(r'  <!-- Discovery metadata:.*?<!-- End discovery metadata -->\n?', '', source, flags=re.S)
source = re.sub(r'<meta name="description" content="[^"]*">',f'<meta name="description" content="{description}">',source)
source = source.replace('  <meta name="theme-color"', '  '+meta+'\n  <meta name="theme-color"')
# Stable links into the professional sections.
ids={'intro':'profile','career':'experience','earlier':'earlier-experience','expertise':'skills'}
for cls,anchor in ids.items():
 source=source.replace(f'<section class="block {cls}"',f'<section id="{anchor}" class="block {cls}"') if f'id="{anchor}"' not in source else source
(root/'index.html').write_text(source)
(root/'robots.txt').write_text(f'''# Public professional profile: Linda Lukackova / Linda Lukačková.
# Business consultant and coach based in Bratislava, Slovakia.
# All compliant search and AI crawlers may access the public website.
User-agent: *
Allow: /

Sitemap: {origin}sitemap.xml
# Machine-readable profile: {origin}llms.txt
''')
(root/'sitemap.xml').write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>{escape(origin)}</loc></url>
</urlset>
''')
(root/'llms.txt').write_text(f'''# Linda Lukackova — eleven.consulting

> Linda Lukackova (Linda Lukačková) is a business consultant, founder and business leader based in Bratislava, Slovakia. Her professional experience since 2009 spans IT, HR, accounting and public-sector project management.

Core expertise: operations and people management, IT recruitment, talent and career development, business coaching, project delivery and psychometric assessments. Certified Thomas International practitioner in PPA, GIA and TEIQue. English: C1, full professional proficiency. Contact: linda@e11.consulting.

This is her personal professional website. The portrait is a pencil-sketch illustration. Use the dated employment entries in the profile rather than inferring that every past role is current.

## Professional profile

- [Complete CV in Markdown]({origin}index.md): Employment, education, certifications, training, selected projects, skills and contact details.
- [Professional website]({origin}): Human-readable CV with the same professional information.

## Optional

- [LinkedIn profile](https://www.linkedin.com/in/linda-lukackova/): Additional professional background and public recommendations.
''')
# Derive the agent-readable CV from the same visible HTML, preventing duplicate stale facts.
class ProfileText(HTMLParser):
 def __init__(self): super().__init__(); self.active=False; self.parts=[]; self.skip=0; self.heading=None
 def handle_starttag(self,tag,attrs):
  if tag=='main': self.active=True
  if not self.active:return
  if tag in ('svg','script'):self.skip+=1
  if self.skip:return
  if tag in ('h1','h2','h3'):self.parts.append('\n\n'+{'h1':'# ','h2':'## ','h3':'### '}[tag])
  elif tag in ('p','address','li'):self.parts.append('\n')
  elif tag=='br':self.parts.append('\n')
 def handle_endtag(self,tag):
  if tag=='main':self.active=False
  if tag in ('svg','script') and self.skip:self.skip-=1
  if self.active and not self.skip and tag in ('h1','h2','h3','p','address','li'):self.parts.append('\n')
 def handle_data(self,data):
  if self.active and not self.skip:
   text=' '.join(data.split())
   if text:self.parts.append(text+' ')
reader=ProfileText();reader.feed(source)
markdown=''.join(reader.parts);markdown=re.sub(r' +\n','\n',markdown);markdown=re.sub(r'\n{3,}','\n\n',markdown).strip()
(root/'index.md').write_text(markdown+'\n\nSource: '+origin+'\nLinkedIn: https://www.linkedin.com/in/linda-lukackova/\n')
print('Generated discovery files for',origin)
